### ISSUE TITLE
Add 2D/3D model loading / conversion to the demo

### ISSUE THREAD

**Issue by timostrating** [LucvandenBrand/WiiDevEnv#15]
It would be nice if we could load a model from for example blender and use that in the demo code.

**Comment by LucvandenBrand** [comment]
Implemented 3D model loading in the latest push to main @timostrating :)
Very flexible, so happy with how it works.
Keeping this ticket open because:

- Current example performance is crappy.
- No texturing / vertex colors yet, should be added (should be easy with the current setup to add).

**Comment by LucvandenBrand** [comment]
Fixed the performance, will close this and create a separate texture ticket.
