### ISSUE TITLE
Separate grrlib into its own subcrate

### ISSUE THREAD

**Issue by Qqwy** [LucvandenBrand/WiiDevEnv#32]
This would have the following advantages:

- Better reusability/separation of concerns;
- A clearer demarcation of what Clippy should and should not check (c.f. #27 );
- The possibility to ban all unsafe code to this subcrate (and ban it everywhere else).

**Comment by LucvandenBrand** [comment]
@Qqwy I started https://github.com/snappy-cobra/grrustlib as a separate repo for the grrlib implementation. If I get to finish it we'll be able to simply include it as a dependency :)

**Comment by LucvandenBrand** [comment]
Sort of did this in the latest texture refactor merge. The separate repo is still something i'd like to do, but I think this ticket can be closed for now.
