### ISSUE TITLE
Add texture support

### ISSUE THREAD

**Issue by LucvandenBrand** [LucvandenBrand/WiiDevEnv#42]
Useful:

- https://github.com/GRRLIB/GRRLIB/blob/master/examples/3D_sample2/source/main.c
- `app/src/raw_data_store.rs`
- `app/src/renderer/indexed_model.rs`
- https://docs.rs/wavefront/0.2.3/wavefront/

**Comment by LucvandenBrand** [comment]
Currently being worked on in [lvdb/texture_support](https://github.com/snappy-cobra/WiiDevEnv/tree/lvdb/texture_support)

**Comment by Qqwy** [comment]
@LucvandenBrand Tip: You can open a 'draft pull request' to indicate that work is ongoing, but already linking issue with branch, giving people the possibility to look at the work, and make it easier to look at CI output
