### ISSUE TITLE
Have a look at the sound output

### ISSUE THREAD

**Issue by LucvandenBrand** [LucvandenBrand/WiiDevEnv#6]
Should be possible with libogc. Good demo would be: looping background music and sounds when the cubes bounce.

**Comment by timostrating** [comment]
It would be nice if we could have a background sound + sounds of things happening in the world. 

Getting the sounds on the Wii in the right format would also be something that needs to be figured out. If this requires a strange format it would be nice if there is a way to convert a standard format such as mp3 or in the worst case midi to the format that is needed. That way we could ask any artist during the game jam to make some sounds.

**Comment by LucvandenBrand** [comment]
@timostrating 

Looks like MP3 playing is relatively simple if we port this to Rust:
https://github.com/devkitPro/wii-examples/tree/master/audio/mp3player

Seems like there are also examples for MOD and OGG: https://github.com/devkitPro/wii-examples/tree/master/audio

I also found this old tutorial for MOD files: http://www.codemii.com/2009/04/21/tutorial-12-using-mod-music-sound/#more-509

**Comment by LucvandenBrand** [comment]
Implemented OGG audio support, which should be enough for us.
